// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/product/pkg/api"
	"github.com/product/pkg/api/handler"
	"github.com/product/pkg/config"
	"github.com/product/pkg/db"
	"github.com/product/pkg/repository"
	"github.com/product/pkg/usecase"
)

// Injectors from wire.go:

func InitializeApi(cfg config.Config) (*api.ServerHttp, error) {
	client, err := db.ConnectToDatabase(cfg)
	if err != nil {
		return nil, err
	}
	productRepository := repository.NewProductRepo(client)
	productUseCase := usecase.NewProductUseCase(productRepository)
	productHandler := handler.NewProductHandler(productUseCase)
	serverHttp := api.NewServerHttp(productHandler)
	return serverHttp, nil
}
